services:

  heroku-cli:
    build: ./heroku
    env_file: ./heroku/.env

  # db:
  #   build: ./db
  #   env_file: .env
  #   volumes:
  #     - t9db:/var/lib/postgresql/data
  #     - ./db:/docker-entrypoint-initdb.d

  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: devapp
    # depends_on:
    #   - db
    # env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/app/src
    command: "npm run test"

volumes:
  vogue-db: {}